channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blinker=1.6.2
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - click=8.1.7
  - colorama=0.4.6
  - flask=3.0.3
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - libffi=3.4.4
  - markupsafe=2.1.3
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - werkzeug=3.0.6
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13